### ISSUE TITLE
Fatal: Not supported ONNX opcode: LogSoftmax

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#457]
**Describe the bug**
I found that the onnx op LogSoftmax has been supported by ncc since commit 120417b. But when I try to convert a simple model with LogSoftmax op using the latest ncc, it failed with the above error, and I am not sure whether it is a bug.
```
nncase Command Line Tools 1.0.0-00e7944
Copyright 2019-2021 Canaan Inc.
1. Import graph...
Fatal: Not supported ONNX opcode: LogSoftmax
```

**Environment (please complete the following information):**
 - OS: Ubuntu20.04
 - nncase version v1.0.0-00e7944

**Comment by zhangyang2057** [comment]
I can run LogSoftmax test cases successfully.
`tests/importer/onnx_/basic/test_logsoftmax.py .....................                                                                                                                                  [100%]

============================================================================================= warnings summary =============================================================================================
tests/importer/onnx_/basic/test_logsoftmax.py::test_logsoftmax[1-None-in_shape0]
  /usr/lib/python3/dist-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    if not isinstance(key, collections.Hashable):

tests/importer/onnx_/basic/test_logsoftmax.py::test_logsoftmax[1-1-in_shape0]
  /home/zhangyang/.local/lib/python3.7/site-packages/onnx/helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    is_iterable = isinstance(value, collections.Iterable)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================ 21 passed, 2 warnings in 141.05s (0:02:21) ================================================================================
`

And with ncc, the test case model can be build successfull.
`
+ /home/zhangyang/workspace/nncase_upload/out/bin/ncc compile -i onnx -t k210 /home/zhangyang/workspace/nncase_x86_64/tests_output/test_logsoftmax_13-None-in_shape0_/test.onnx test.kmodel --input-type default --dump-ir --dump-asm --dump-dir output
nncase Command Line Tools 1.0.0-00e7944b
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...
WARN: Cannot find a decompiler for section .rdata
WARN: Cannot find a decompiler for section .text

SUMMARY
INPUTS
0	input	f32[1,3,16,16]
OUTPUTS
0	output	f32[1,3,16,16]

MEMORY USAGES
.input	   3.00 KB	(3072 B)
.output	   3.00 KB	(3072 B)
.data	   6.19 KB	(6336 B)
MODEL	 960.00 B	(960 B)
TOTAL	  13.12 KB	(13440 B)

`

**Comment by zhangyang2057** [comment]
I'm sure that LogSoftmax op has been supported in the latest nncase. 
Could you tell me where is your ncc from?

**Comment by annosoo** [comment]
my ncc is from [here](https://github.com/kendryte/nncase/actions/runs/1499201311)

**Comment by zhangyang2057** [comment]
I used your ncc with 1.0.0-00e7944, but it can build the LogSoftmax model successfully.
```
+ /home/zhangyang/Downloads/tmp/bin/ncc compile -i onnx -t k210 /home/zhangyang/workspace/nncase_x86_64/tests_output/test_logsoftmax_13-None-in_shape0_/test.onnx test.kmodel --input-type default --dump-ir --dump-asm --dump-dir output
nncase Command Line Tools 1.0.0-00e7944
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...
WARN: Cannot find a decompiler for section .rdata
WARN: Cannot find a decompiler for section .text

SUMMARY
INPUTS
0	input	f32[1,3,16,16]
OUTPUTS
0	output	f32[1,3,16,16]

MEMORY USAGES
.input	   3.00 KB	(3072 B)
.output	   3.00 KB	(3072 B)
.data	   6.19 KB	(6336 B)
MODEL	 960.00 B	(960 B)
TOTAL	  13.12 KB	(13440 B)
```

**Comment by zhangyang2057** [comment]
I tried on both ubuntu 18.04 and 20.04, both are normal.
Could you please upload your onnx model with LogSoftmax op?

**Comment by annosoo** [comment]
here are my test model and used ncc
[model.zip](https://github.com/kendryte/nncase/files/7617503/model.zip)

[ncc.zip](https://github.com/kendryte/nncase/files/7617504/ncc.zip)
here is my ncc compile command
`./ncc compile -i onnx -t k210 model.onnx model.kmodel`

**Comment by zhangyang2057** [comment]
ncc 1.0.0-00e7944 with can build your model.onnx successfully.
```
./bin/ncc compile -i onnx -t k210 model.onnx test.kmodel --input-type default --dump-ir --dump-asm --dump-dir output
nncase Command Line Tools 1.0.0-00e7944
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...
WARN: Cannot find a decompiler for section .rdata
WARN: Cannot find a decompiler for section .text

SUMMARY
INPUTS
0	input	f32[1,1,28,28]
OUTPUTS
0	output	f32[1,10]

MEMORY USAGES
.input	   3.06 KB	(3136 B)
.output	  40.00 B	(40 B)
.data	 120.00 B	(120 B)
MODEL	  31.72 KB	(32480 B)
TOTAL	  34.94 KB	(35776 B)

```

**Comment by annosoo** [comment]
I used the same ncc command you provided, but it still failed on my machine.
`./ncc compile -i onnx -t k210 model.onnx model.kmodel --input-type default --dump-ir --dump-asm --dump-dir dump`
```
nncase Command Line Tools 1.0.0-00e7944
Copyright 2019-2021 Canaan Inc.
1. Import graph...
Fatal: Not supported ONNX opcode: LogSoftmax
```
I am confused about what cause the issue, but the op indeed doesn't work.

**Comment by zhangyang2057** [comment]
I think maybe you misused the ncc. Your ncc command line is the 00e7944, but the nncase library is too old to include the LogSoftmax op.
 
Try the following 
```
$ ldd bin/ncc 
	linux-vdso.so.1 (0x00007ffd0a359000)
	libnncase.so => /home/zhangyang/workspace/test/logsoftmax/00e7944/bin/../lib/libnncase.so (0x00007f651bd81000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f651b974000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f651b75c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f651b36b000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f651b167000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f651af5f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f651ad40000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f651aafd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f651a75f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f651cfe9000)
```

So ncc depends on /home/zhangyang/workspace/test/logsoftmax/00e7944/bin/../lib/libnncase.so

Then get the md5 value of nncase library.
```
$ md5sum /home/zhangyang/workspace/test/logsoftmax/00e7944/bin/../lib/libnncase.so
c50e3903868e776b2907c38353b18279  /home/zhangyang/workspace/test/logsoftmax/00e7944/bin/../lib/libnncase.so
```

**Comment by annosoo** [comment]
you are right. Now it can be successfully compiled since I updated my environment, thanks!
